#! /usr/bin/bash
exe=`realpath "$0"`
dir=`dirname "$exe"`
cd "$dir"
for ver in 1.{0..11}; do
    echo "############## julia-$ver"
    rm -f Manifest.toml
    test -r ".Manifest-$ver.toml" && cp -pf ".Manifest-$ver.toml" Manifest.toml
    julia +$ver --project --check-bounds=yes --depwarn=yes --color=yes \
        -e 'import Pkg; Pkg.instantiate(); include("test/runtests.jl")'
    mv -f Manifest.toml ".Manifest-$ver.toml"
done
